# Generated by Django 5.2.7 on 2026-03-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_email_adminactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=120)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('host_user', models.CharField(blank=True, max_length=255)),
                ('host_password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('timeout', models.PositiveIntegerField(default=20)),
                ('from_email', models.EmailField(default='no-reply@aura.local', max_length=254)),
                ('test_recipient_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de correo',
                'verbose_name_plural': 'Configuraciones de correo',
            },
        ),
    ]
