# Generated by Django 5.2.7 on 2026-03-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0003_emailserverconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='usuarios_active_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['date_joined'], name='usuarios_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['last_login'], name='usuarios_last_login_idx'),
        ),
    ]
