# Generated by Django 5.2.12 on 2026-03-30 02:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_default_plans_and_features(apps, schema_editor):
    Feature = apps.get_model('usuarios', 'Feature')
    Plan = apps.get_model('usuarios', 'Plan')
    PlanFeature = apps.get_model('usuarios', 'PlanFeature')

    import_rows_feature, _ = Feature.objects.get_or_create(
        code='import_max_rows',
        defaults={
            'name': 'Maximo de filas por importacion',
            'description': 'Cantidad maxima de filas permitidas en una carga historica.',
            'value_type': 'int',
            'is_highlighted': True,
            'is_active': True,
        },
    )

    free_plan, _ = Plan.objects.get_or_create(
        slug='free',
        defaults={
            'name': 'Free',
            'description': 'Plan base para nuevos usuarios.',
            'is_active': True,
            'is_default': True,
            'sort_order': 10,
        },
    )
    pro_plan, _ = Plan.objects.get_or_create(
        slug='pro',
        defaults={
            'name': 'Pro',
            'description': 'Plan con mayor capacidad de importacion y funciones avanzadas.',
            'is_active': True,
            'is_default': False,
            'sort_order': 20,
        },
    )

    PlanFeature.objects.update_or_create(
        plan=free_plan,
        feature=import_rows_feature,
        defaults={'value_int': 2000, 'value_bool': False, 'value_text': ''},
    )
    PlanFeature.objects.update_or_create(
        plan=pro_plan,
        feature=import_rows_feature,
        defaults={'value_int': 5000, 'value_bool': False, 'value_text': ''},
    )


def unseed_default_plans_and_features(apps, schema_editor):
    Feature = apps.get_model('usuarios', 'Feature')
    Plan = apps.get_model('usuarios', 'Plan')

    Feature.objects.filter(code='import_max_rows').delete()
    Plan.objects.filter(slug__in=['free', 'pro']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_adminactionlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('bool', 'Booleano'), ('int', 'Entero'), ('text', 'Texto')], default='bool', max_length=12)),
                ('is_highlighted', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField(default=False)),
                ('value_int', models.PositiveIntegerField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_values', to='usuarios.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='usuarios.plan')),
            ],
            options={
                'verbose_name': 'Valor de feature por plan',
                'verbose_name_plural': 'Valores de feature por plan',
                'ordering': ['feature__name'],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='UserPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_plan_assignments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='usuarios.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion de plan',
                'verbose_name_plural': 'Asignaciones de planes',
                'ordering': ['-is_active', '-starts_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_plan_active_idx'), models.Index(fields=['plan', 'is_active'], name='plan_active_idx')],
            },
        ),
        migrations.RunPython(seed_default_plans_and_features, unseed_default_plans_and_features),
    ]
