# Generated by Django 6.0.3 on 2026-04-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_plan_precio_pagoPayPhone'),
        ('usuarios', '0011_userplanassignment_tipo'),
    ]

    operations = [
    ]
