# Generated by Django 6.0.3 on 2026-04-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_merge_20260418_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanassignment',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
