# Generated by Django 6.0.5 on 2026-07-24 20:23

from django.db import migrations, models


def personalizada_a_conservadora(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(projection_mode='personalizada').update(projection_mode='conservadora')


def conservadora_a_personalizada(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(projection_mode='conservadora').update(projection_mode='personalizada')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='projection_mode',
            field=models.CharField(choices=[('simple', 'Simple'), ('automatica', 'Inteligente'), ('conservadora', 'Conservadora')], default='automatica', max_length=16),
        ),
        migrations.RunPython(personalizada_a_conservadora, conservadora_a_personalizada),
    ]
