# Generated by Django 5.2.16 on 2026-07-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_usuario_projection_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('privacy_notice', 'Aviso de privacidad'), ('terms_financial', 'Terminos y descargo financiero')], max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='registration', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceptacion legal',
                'verbose_name_plural': 'Aceptaciones legales',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['document_type', 'version', 'accepted_at'], name='legal_doc_version_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document_type', 'version'), name='unique_user_legal_version')],
            },
        ),
    ]