# Generated by Django 6.0.2 on 2026-03-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('vivienda', 'Vivienda'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('salud', 'Salud'), ('educacion', 'Educación'), ('entretenimiento', 'Entretenimiento'), ('ropa', 'Ropa'), ('servicios', 'Servicios básicos'), ('tecnologia', 'Tecnología'), ('deudas', 'Deudas'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_cuotas', models.PositiveIntegerField()),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diferido',
                'verbose_name_plural': 'Diferidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GastoCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('vivienda', 'Vivienda'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('salud', 'Salud'), ('educacion', 'Educación'), ('entretenimiento', 'Entretenimiento'), ('ropa', 'Ropa'), ('servicios', 'Servicios básicos'), ('tecnologia', 'Tecnología'), ('deudas', 'Deudas'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_corrientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Corriente',
                'verbose_name_plural': 'Gastos Corrientes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GastoNoCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('vivienda', 'Vivienda'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('salud', 'Salud'), ('educacion', 'Educación'), ('entretenimiento', 'Entretenimiento'), ('ropa', 'Ropa'), ('servicios', 'Servicios básicos'), ('tecnologia', 'Tecnología'), ('deudas', 'Deudas'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_no_corrientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto No Corriente',
                'verbose_name_plural': 'Gastos No Corrientes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
