# Generated by Django 6.0.2 on 2026-03-27 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('vivienda', 'Vivienda'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('salud', 'Salud'), ('educacion', 'Educación'), ('entretenimiento', 'Entretenimiento'), ('ropa', 'Ropa'), ('servicios', 'Servicios básicos'), ('tecnologia', 'Tecnología'), ('deudas', 'Deudas'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], max_length=30)),
                ('limite_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['categoria'],
                'unique_together': {('usuario', 'categoria')},
            },
        ),
    ]
