# Generated by Django 6.0.2 on 2026-03-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_presupuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diferido',
            name='categoria',
            field=models.CharField(default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='gastocorriente',
            name='categoria',
            field=models.CharField(default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='gastonocorriente',
            name='categoria',
            field=models.CharField(default='otro', max_length=50),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(default='📦', max_length=10)),
                ('limite_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
