# Generated by Django 6.0.2 on 2026-03-27 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_diferido_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_mes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo mes anterior',
                'verbose_name_plural': 'Saldos mes anterior',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('usuario', 'anio', 'mes')},
            },
        ),
    ]
