# Generated by Django 6.0.2 on 2026-03-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_saldomes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldomes',
            options={'ordering': ['-anio', '-mes'], 'verbose_name': 'Saldo mes', 'verbose_name_plural': 'Saldos mes'},
        ),
        migrations.AddField(
            model_name='saldomes',
            name='recalculos_hoy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saldomes',
            name='ultimo_recalculo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
