# Generated by Django 6.0.3 on 2026-04-03 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_ingresopuntual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diferido',
            index=models.Index(fields=['usuario', 'activo', 'fecha_inicio', 'fecha_fin'], name='dif_usr_rango_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocorriente',
            index=models.Index(fields=['usuario', 'activo', 'fecha_inicio'], name='gc_usr_ini_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocorriente',
            index=models.Index(fields=['usuario', 'fecha_fin'], name='gc_usr_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='gastonocorriente',
            index=models.Index(fields=['usuario', 'fecha'], name='gasto_nc_usuario_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['usuario', 'activo', 'fecha_inicio'], name='ing_usr_ini_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['usuario', 'fecha_fin'], name='ing_usr_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresopuntual',
            index=models.Index(fields=['usuario', 'fecha'], name='ip_usr_fecha_idx'),
        ),
    ]
