# Generated by Django 6.0.5 on 2026-07-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_cuentas_personas_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocorriente',
            name='tipo_monto',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable')], default='fijo', max_length=10),
        ),
        migrations.CreateModel(
            name='GastoCorrienteEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('monto_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='finanzas.gastocorriente')),
            ],
            options={
                'verbose_name': 'Ejecución de gasto variable',
                'verbose_name_plural': 'Ejecuciones de gastos variables',
                'ordering': ['-anio', '-mes'],
                'indexes': [models.Index(fields=['gasto', 'anio', 'mes'], name='gce_gasto_periodo_idx')],
                'unique_together': {('gasto', 'anio', 'mes')},
            },
        ),
    ]
