# Generated by Django 6.0.5 on 2026-07-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_gastocorriente_tipo_monto_gastocorrienteejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('limite_cercano', 'Cerca del límite (≥75%)'), ('presupuesto_superado', 'Presupuesto superado (≥100%)'), ('variables_pendientes', 'Gastos variables por registrar este mes')], max_length=30),
        ),
    ]
