# Generated by Django 6.0.5 on 2026-07-27 16:27

import datetime
from django.db import migrations, models


def poblar_fecha(apps, schema_editor):
    # Lo ya registrado (un total por mes) pasa a ser un consumo con fecha en
    # el primer dia de su mes, para no perder nada.
    Ejec = apps.get_model('finanzas', 'GastoCorrienteEjecucion')
    for e in Ejec.objects.filter(fecha__isnull=True):
        e.fecha = datetime.date(e.anio, e.mes, 1)
        if not e.descripcion:
            e.descripcion = 'Registrado'
        e.save(update_fields=['fecha', 'descripcion'])


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastocorrienteejecucion',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Consumo de gasto variable', 'verbose_name_plural': 'Consumos de gastos variables'},
        ),
        migrations.AlterUniqueTogether(
            name='gastocorrienteejecucion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gastocorrienteejecucion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gastocorrienteejecucion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(poblar_fecha, migrations.RunPython.noop),
    ]
