# Generated by Django 5.2.13 on 2026-07-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0015_alter_gastocorrienteejecucion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='ultimo_aviso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
