# Generated by Django 6.0.5 on 2026-08-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_notificacion_ultimo_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='diferido',
            name='pagada_en',
            field=models.DateField(blank=True, null=True),
        ),
    ]
