# Generated by Django 6.0.2 on 2026-03-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tasa_anual_minima', models.DecimalField(decimal_places=2, help_text='Tasa anual mínima en %', max_digits=5)),
                ('tasa_anual_maxima', models.DecimalField(decimal_places=2, help_text='Tasa anual máxima en %', max_digits=5)),
                ('plazo_maximo_meses', models.PositiveIntegerField(default=240)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Casa en Las Condes, iPhone 15 Pro', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_anual', models.DecimalField(decimal_places=2, help_text='Tasa anual en %', max_digits=5)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_intereses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_inicio', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.banco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
